Fixed two errors in js: [24/Jun/2016 02:51:39] "POST /api/v2/page_content_items/ HTTP/1.1" 400 69 [24/Jun/2016 02:51:39] "POST /api/v2/page_content_items/ HTTP/1.1" 400 69
1. Wrong content_item_id, /api/v2/page_content_item/10/change ends with action not element id
2. Wrong type for updating element

One rest full api error:
Internal Server Error: /api/v2/page_content_items/7/move/
Traceback (most recent call last):
  File "/Users/admin/projects/vitaly/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/admin/projects/vitaly/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/admin/projects/vitaly/env/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/admin/projects/vitaly/env/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/admin/projects/vitaly/env/lib/python3.5/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/Users/admin/projects/vitaly/env/lib/python3.5/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/admin/projects/vitaly/fibertst/fiber/rest_api/views.py", line 134, in put
    before_page_content_item_id = request.DATA.get('before_page_content_item_id')
  File "/Users/admin/projects/vitaly/env/lib/python3.5/site-packages/rest_framework/request.py", line 353, in __getattribute__
    return super(Request, self).__getattribute__(attr)
  File "/Users/admin/projects/vitaly/env/lib/python3.5/site-packages/rest_framework/request.py", line 364, in DATA
    '`request.DATA` has been deprecated in favor of `request.data` '
NotImplementedError: `request.DATA` has been deprecated in favor of `request.data` since version 3.0, and has been fully removed as of version 3.2.